<?php

/**
 * Implements hook_permission().
 */
function bugcatchlog_permission() {
  return array(
    'config bugcatchlog' => array(
      'title' => t('Configure BugCatch.'),
      'description' => t('Configure access to Bug Catch service.'),
    ),
  );
}

/**
 * Implements hook_menu().
 */
function bugcatchlog_menu() {
  return array(
    'admin/config/bugcatchlog' => array(
      'title' => 'Configure BugCatch',
      'description' => 'Configure access to Bug Catch service.',
      'access arguments' => array('config bugcatchlog'),
      'page callback' => 'drupal_get_form',
      'page arguments' => 'bugcatchlog_config_form',
      'file' => 'bugcatchlog.pages.inc',
    ),
  );
}

/**
 * Utility function to read module configuration.
 */
function bugcatchlog_config($var) {
  $defaults = array(
    'service_url' => 'https://bugcatches.com/app_api.php/api/errors.json',
    'service_key' => '',
  );
  if (!isset($defaults[$var])) {
    return NULL;
  }
  return variable_get("bugcatchlog_$var", $defaults[$var]);
}

/**
 * Implements hook_watchdog().
 */
function bugcatchlog_watchdog() {}
